name: main
on:
  push:
    branches:
    - main
jobs:
  release:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        submodules: recursive
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v1
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1
    - name: Login to DockerHub
      uses: docker/login-action@v1 
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    - name: Build and push container image
      uses: docker/build-push-action@v2
      with:
        push: true
        tags: |
          ${{ secrets.DOCKERHUB_USERNAME }}/app:latest
          ${{ secrets.DOCKERHUB_USERNAME }}/app:${{ github.sha }}
    - name: Checkout prod
      uses: actions/checkout@v2
      with:
        repository: ${{ secrets.GH_ORG }}/argo-express-prod
        persist-credentials: false
        fetch-depth: 0
    - name: Update manifests
      run: |
        sleep 1
        # cat manifests/deployment.yaml | sed -e "s@- ${{ secrets.DOCKERHUB_USERNAME }}/app:.*@- ${{ secrets.DOCKERHUB_USERNAME }}/app:${{ github.sha }}@g" | tee manifests/deployment.yaml
        # sed -i -e 's/\(image:\).*/\1 guetaamit\/app:v7/g' manifests/deployment.yaml
        sed -i -e 's/\(guetaamit\/app:\).*/guetaamit\/app:${{ github.sha }}/g' manifests/deployment.yaml
        cat manifests/deployment.yaml
        git config --global user.email "${{ secrets.GH_ORG }}@express.com"
        git config --global user.name "${{ secrets.GH_ORG }}"
        git add .
        git status
        git commit -m "Promoting express-server production ${{ github.sha }}"
    - name: Push prod
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GH_TOKEN }}
        repository: ${{ secrets.GH_ORG }}/argo-express-prod
