name: pr-open
on:
  pull_request:
    branches:
    - main

env:
  PROJECT_ID: ${{ secrets.GKE_PROJECT }}
  GKE_CLUSTER: flask-cluster    # Add your cluster name here.
  GKE_ZONE: europe-west2-a   # Add your cluster zone here.

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        submodules: recursive
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v1
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1
    - name: Login to DockerHub
      uses: docker/login-action@v1 
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    - name: Build and push container image
      uses: docker/build-push-action@v2
      with:
        push: true
        tags: |
          ${{ secrets.DOCKERHUB_USERNAME }}/preview:pr-${{ github.event.pull_request.number }}
          
    
    - id: 'auth'
      name: 'Authenticate to Google Cloud'
      uses: 'google-github-actions/auth@v0'
      with:
        credentials_json: '${{ secrets.GKE_SA_KEY }}'
    
        # Get the GKE credentials so we can deploy to the cluster
    - uses: google-github-actions/get-gke-credentials@v0
      with:
        cluster_name: ${{ env.GKE_CLUSTER }}
        location: ${{ env.GKE_ZONE }}

    - name: Deploy preview
      run: |
        # Install vCluster
        ls
        curl -s -L "https://github.com/loft-sh/vcluster/releases/latest" | sed -nE 's!.*"([^"]*vcluster-linux-amd64)".*!https://github.com\1!p' | xargs -n 1 curl -L -o vcluster && chmod +x vcluster;
        sudo mv vcluster /usr/local/bin;
        
        # Create a cluster
        vcluster create preview-pr-${{ github.event.pull_request.number }} --namespace prs --expose 
        vcluster connect preview-pr-${{ github.event.pull_request.number }} --namespace prs
        export KUBECONFIG=$PWD/kubeconfig.yaml
        sleep 5
        kubectl get ingresses

        # Deploy
        cd preview_manifest
        # grep -rl 'express-server-preview' . | xargs sed -i '' 's/express-server-preview/express-server-preview-${{ github.event.pull_request.number }}/g'
        sed -i 's/express-server-preview/express-server-preview-${{ github.event.pull_request.number }}/g' deployment.yaml
        cat deployment.yaml
        sed -i 's/express-server-preview/express-server-preview-${{ github.event.pull_request.number }}/g' ingress.yaml
        sed -i 's/\(image: \)\(.*\)/\1${{ secrets.DOCKERHUB_USERNAME }}/preview:pr-${{ github.event.pull_request.number }}/' deployment.yaml
        cat deployment.yaml
        kubectl apply -f deployment.yaml
        kubectl apply -f ingress.yaml
        # kubectl rollout status deployment devops-toolkit
    - name: Test
      run: |
        echo "I was to lazy to write tests"